import os
import re
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

# ==============================
# GITHUB FETCH
# ==============================

def github_raw_url(blob_url: str) -> str:
    return (
        blob_url
        .replace("github.com", "raw.githubusercontent.com")
        .replace("/blob/", "/")
    )


def extract_satd_line_number(url: str) -> int:
    """This function is used to extract the SATD line number from a GitHub URL (#L123)."""
    match = re.search(r"#L(\d+)", url)
    return int(match.group(1)) if match else None


def fetch_full_file(url: str, token: str = None) -> str:
    raw_url = github_raw_url(url.split("#")[0])
    headers = {}
    if token:
        headers["Authorization"] = f"token {token}"

    response = requests.get(raw_url, headers=headers)
    if response.status_code != 200:
        print(f"❌ Failed to fetch: {url} (HTTP {response.status_code})")
        return ""
    return response.text


# ==============================
# FILE TYPE CONFIG
# ==============================

PLAIN_TEXT_EXTENSIONS = {".md", ".txt", ".rst", ".adoc"}

SKIP_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
    ".pdf", ".zip", ".tar", ".gz", ".jar", ".class", ".pyc",
    ".lock", ".sum", ".snap",
}


def _get_extension(url: str) -> str:
    path = url.split("#")[0].split("?")[0]
    _, ext = os.path.splitext(path)
    return ext.lower()


# ==============================
# CLEANING UTILITIES (SATD-SAFE)
# ==============================

def _remove_blank_lines(text: str, max_consecutive: int = 2) -> str:
    pattern = r"(\n\s*){" + str(max_consecutive + 1) + r",}"
    return re.sub(pattern, "\n" * max_consecutive, text)


def _strip_license_header(lines: list[str], satd_idx: int | None) -> list[str]:
    LICENSE_KEYWORDS = {"license", "copyright", "spdx"}

    start = next((i for i, l in enumerate(lines) if l.strip()), None)
    if start is None:
        return lines

    # 🔥 Protect SATD if inside header
    if satd_idx is not None and satd_idx <= start + 60:
        return lines

    first = lines[start].strip()

    block_openers = {"/*", "/**", "<!--", "#!", "{#", "(*", "'''", '"""'}
    block_closers = {"*/", "-->", "#}", "*)", "'''", '"""'}

    is_block = any(first.startswith(op) for op in block_openers)
    is_hash_block = first.startswith("#")

    if not (is_block or is_hash_block):
        return lines

    for i in range(start, min(start + 60, len(lines))):
        lower = lines[i].strip().lower()
        if any(kw in lower for kw in LICENSE_KEYWORDS):
            for j in range(i, min(i + 60, len(lines))):
                if satd_idx is not None and j >= satd_idx:
                    return lines

                stripped = lines[j].strip()
                if any(stripped.endswith(cl) for cl in block_closers):
                    return lines[j + 1 :]
                if is_hash_block and j > start and not stripped.startswith("#"):
                    return lines[j:]
            break

    return lines


def _strip_generated_markers(lines: list[str], satd_idx: int | None) -> list[str]:
    markers = [
        "do not edit", "auto-generated", "autogenerated",
        "generated by", "code generated", "@generated"
    ]

    result = []
    for i, line in enumerate(lines):
        if satd_idx is not None and i == satd_idx:
            result.append(line)
            continue

        if any(m in line.lower() for m in markers):
            continue

        result.append(line)

    return result


def _strip_long_strings(lines: list[str], satd_idx: int | None, threshold: int = 300) -> list[str]:
    result = []
    for i, line in enumerate(lines):
        if satd_idx is not None and i == satd_idx:
            result.append(line)
            continue

        stripped = line.strip()
        if len(stripped) > threshold and re.match(r'^["\']?[A-Za-z0-9+/=_\-]{' + str(threshold) + r',}', stripped):
            result.append("  # [long encoded string omitted]\n")
        else:
            result.append(line)

    return result

def extract_satd_window(text: str, url: str, window: int = 80) -> str:
    satd_line = extract_satd_line_number(url)
    if not satd_line:
        return text[:3000]

    lines = text.splitlines()
    idx = satd_line - 1

    start = max(0, idx - window)
    end   = min(len(lines), idx + window)

    return "\n".join(lines[start:end])
# ==============================
# MAIN CLEAN FUNCTION
# ==============================

def clean_file_content(raw_content: str, url: str) -> str:

    lines = raw_content.splitlines(keepends=True)

    satd_line = extract_satd_line_number(url)
    satd_idx = satd_line - 1 if satd_line else None

    lines = _strip_license_header(lines, satd_idx)
    lines = _strip_generated_markers(lines, satd_idx)
    lines = _strip_long_strings(lines, satd_idx)

    cleaned = "".join(lines)
    cleaned = _remove_blank_lines(cleaned, max_consecutive=3)

    # 🔥 Ensure SATD is present
    satd_text = None
    if satd_idx is not None:
        original_lines = raw_content.splitlines()
        if satd_idx < len(original_lines):
            satd_text = original_lines[satd_idx]

            if satd_text.strip() not in cleaned:
                cleaned = satd_text + "\n\n" + cleaned

    return cleaned.strip()

# ==============================
# MAIN PIPELINE
# ==============================

def process_excel(input_file: str, output_file: str, github_token: str = None, max_chars: int = 12_000):
    df = pd.read_excel(input_file)
    content_files = []

    for idx, row in df.iterrows():
        url = str(row.get("url", "") or "").strip()
        print(f"\n🔍 [{idx + 1}/{len(df)}] {url[:90]}")

        if not url or "github.com" not in url:
            print("   ⚠ Invalid URL")
            content_files.append(None)
            continue

        try:
            raw = fetch_full_file(url, github_token)
            if not raw:
                content_files.append(None)
                continue

            cleaned = clean_file_content(raw, url)

            original_chars = len(raw)
            cleaned_chars = len(cleaned)
            reduction = 100 * (1 - cleaned_chars / original_chars) if original_chars else 0

            print(f"   ✓ {original_chars:,} → {cleaned_chars:,} chars ({reduction:.0f}% removed)")

            content_files.append(cleaned)

        except Exception as e:
            print(f"   ❌ Error: {e}")
            content_files.append(f"[error: {e}]")

    df["content_file"] = content_files
    df.to_excel(output_file, index=False)
    print(f"\n✅ Done. Saved to: {output_file}")


# ==============================
# RUN
# ==============================

if __name__ == "__main__":
    process_excel(
        input_file="./data/SATD_Context_summary.xlsx",
        output_file="./data/SATD_Contexts_Final.xlsx", #./data/SAT_Context_summary.xlsx
        github_token=os.getenv("GITHUB"),
        max_chars=12_000,
    )